name = "leif-api"
compatibility_date = "2023-05-12"
main = "src/index.ts"

routes = [{ pattern = "api.leif.support", custom_domain = true }]

[vars]
TZ = "UTC"

# The necessary secrets are:
# - ENTSOE_TOKEN
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
