name = "leif-api"
compatibility_date = "2023-05-12"
main = "src/index.ts"

routes = ["leif.support/api*"]

[vars]
TZ = "UTC"

# The necessary secrets are:
# - ENTSOE_TOKEN
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
